project:
  type: website

website:
  title: 'UHC - HCUP Resource'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Manuals
        menu:
        - href: pages/manuals/parquet/index.qmd
          text: "Parquet"  

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual
